### ISSUE TITLE
more than one saws:contains in a work record leads to error in text view?

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#953]
In records with more than one saws:contains, there is a problem with the text view (at least I think that's the reason....), for example http://betamasaheft.eu/works/LIT1233Cantic/text
(also LIT1325egziab or LIT1219Bible)

HTTP ERROR 500
Problem accessing /exist/apps/BetMas/works/LIT1233Cantic/text. Reason:

    Server Error
Caused by:
javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMas/works/LIT1233Cantic/text: exerr:ERROR XPTY0004: The actual cardinality for parameter 1 does not match the cardinality declared in the function's signature: string($arg as item()?) xs:string. Expected cardinality: zero or one, got 2. [at line 978, column 197, source: /db/apps/BetMas/modules/item.xqm]
In function:
	item:RestText(item()*, xs:integer*, xs:integer*) [318:23:/db/apps/BetMas/modules/item.xqm]
	restItem:ITEM(item()*, item()*, item()*, xs:integer*, xs:integer*, xs:string*) [90:1:/db/apps/BetMas/modules/items.xql]
	restItem:gettext(xs:string*, xs:string*, xs:integer*, xs:integer*, xs:string*) [-1:-1:/db/apps/BetMas/modules/items.xql]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:724)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678)
	at java.lang.Thread.run(Thread.java:748)

**Comment by PietroLiuzzo** [comment]
well spotted, it was saws:contains.
should be fixed now.
